package com.example.activeperception.acquire

import kotlin.math.abs
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Goldens generated by sense/shin_metric_ref.py (NumPy mirror of Metric_Our.m,
 * github.com/UkcheolShin/Noise-AwareCameraExposureControl master):
 * `python shin_metric_ref.py` prints the f/meanI rows embedded below.
 * Image generators here are kept in lockstep with that file (same LCG, sizes,
 * seeds) so both sides hash out identical uint8 planes.
 */
class ShinMetricTest {

    private val w = 40
    private val h = 40

    /** 31-bit LCG shared with shin_metric_ref.py — identical pixels both sides. */
    private class Lcg(private var s: Long) {
        fun next(): Int {
            s = (s * 1103515245L + 12345L) and 0x7FFFFFFFL
            return (s ushr 16).toInt()
        }
    }

    private fun flat128() = FloatArray(w * h) { 128f }
    private fun ramp() = FloatArray(w * h) { (it % w) * 255f / (w - 1) }
    private fun lcgNoise(): FloatArray {
        val g = Lcg(12345L)
        return FloatArray(w * h) { (g.next() % 256).toFloat() }
    }
    private fun stepEdge() = FloatArray(w * h) { if (it % w < w / 2) 60f else 200f }
    private fun stepNoisy(): FloatArray {
        val g = Lcg(777L)
        val base = stepEdge()
        return FloatArray(w * h) { (base[it] + (g.next() % 121 - 60)).coerceIn(0f, 255f) }
    }

    private fun assertRel(expected: Double, actual: Double) =
        assertEquals(expected, actual, abs(expected) * 1e-3)

    @Test fun goldenFlat() = assertRel(-0.026737368263, ShinMetric.score(flat128(), w, h))
    @Test fun goldenRamp() = assertRel(0.394966893326, ShinMetric.score(ramp(), w, h))
    @Test fun goldenLcgNoise() = assertRel(-18.540886873645, ShinMetric.score(lcgNoise(), w, h))
    @Test fun goldenStepEdge() = assertRel(0.444410617325, ShinMetric.score(stepEdge(), w, h))
    @Test fun goldenStepNoisy() = assertRel(-8.155240205422, ShinMetric.score(stepNoisy(), w, h))

    @Test fun goldenMeanIntensity() {
        assertEquals(128.0, ShinMetric.meanIntensity(flat128()), 1e-9)
        assertEquals(127.5, ShinMetric.meanIntensity(ramp()), 1e-3)
        assertEquals(129.4325, ShinMetric.meanIntensity(lcgNoise()), 1e-9)
        assertEquals(131.608125, ShinMetric.meanIntensity(stepNoisy()), 1e-9)
    }

    /** Structure beats flatness: a sharp step edge outscores a flat plane. */
    @Test fun sharpEdgeBeatsFlat() {
        assertTrue(ShinMetric.score(stepEdge(), w, h) > ShinMetric.score(flat128(), w, h))
    }

    /**
     * The noise-AWARE property that separates Shin from plain gradient metrics:
     * heavy noise RAISES the gradient term (5.80 vs 0.50 on these planes) yet
     * the sigma penalty drives the total down.
     */
    @Test fun heavyNoiseLowersScore() {
        assertTrue(ShinMetric.score(stepEdge(), w, h) > ShinMetric.score(stepNoisy(), w, h))
    }

    /** Pure noise scores below every structured plane. */
    @Test fun pureNoiseRanksLast() {
        val noise = ShinMetric.score(lcgNoise(), w, h)
        assertTrue(noise < ShinMetric.score(flat128(), w, h))
        assertTrue(noise < ShinMetric.score(ramp(), w, h))
        assertTrue(noise < ShinMetric.score(stepEdge(), w, h))
    }

    /** BT.601 ints/1000 with integer division — MeasurementController.meanLumaRatio. */
    @Test fun lumFromArgbMatchesControllerWeights() {
        val px = intArrayOf(
            0xFF804020.toInt(), 0xFFFFFFFF.toInt(), 0xFF000000.toInt(),
            0xFF0000FF.toInt(), 0xFF00FF00.toInt(), 0xFFFF0000.toInt())
        val lum = ShinMetric.lumFromArgb(px, 6, 1)
        val expected = floatArrayOf(79f, 255f, 0f, 29f, 149f, 76f)
        for (i in px.indices) assertEquals(expected[i], lum[i], 0f)
    }
}
